# Generated by Django 6.0.4 on 2026-04-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='internship_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='internship_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
