# Generated by Django 6.0.4 on 2026-04-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0003_alter_student_internship_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ILES.student'),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='activities',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='challenges',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='date_submitted',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='skills_learned',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
