# Generated by Django 6.0.4 on 2026-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0004_student_reg_no_alter_internshipplacement_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
