# Generated by Django 6.0.4 on 2026-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES', '0007_remove_evaluation_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
